# Generated by Django 3.2.20 on 2023-09-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../default_profile_nhnsof', upload_to='images/'),
        ),
    ]
